#docker run --privileged --shm-size 1g -d -p 8080:10000 -e VNC_PASSWD=password -e PORT=10000 -e AUDIO_PORT=1699 -e WEBSOCKIFY_PORT=6900 -e VNC_PORT=5900 -e SCREEN_WIDTH=1024 -e SCREEN_HEIGHT=768 -e SCREEN_DEPTH=24 moyash/novnc-ros-desktop:melodic
services:
  vpsm:
    build: .
    privileged: true
    shm_size: 128gb
    ports:
      - "4000:4000"
    environment:
      - USER_PWD=AliAly032230
      - USER_NAME=shakugan
